version: '2'

services: 
  nginx:
    image: nginx
    depends_on: 
      - pootle
    volumes:
      - ./nginx/pootle.template:/etc/nginx/conf.d/pootle.template
    ports:
      - "8080:80"
    volumes_from: 
      - pootle
    environment: 
      - NGINX_HOST=pootle.docker
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/pootle.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  pootle:
    build:
      context: pootle
      dockerfile: Dockerfile
    depends_on: 
      - redis
      - mysql
    volumes:
      - l10n-ter:/l10n_ter
      - pootle-po:/srv/pootle/po
      - pootle-git:/srv/pootle/git-clones
    environment:
      - SECRET_KEY=SET THIS TO A DJANGO SECRET KEY
    env_file:
      - etc/environment.yml
  mysql:
    image: mariadb:10.3
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;'
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - etc/environment.yml
  redis:
    image: redis

volumes:
  mysql-data:
  l10n-ter:
  pootle-po:
  pootle-git:
